AllCops:
  TargetRubyVersion: 2.4
require: rubocop-rspec
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4
Layout/BeginEndAlignment:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Layout/CaseIndentation:
  EnforcedStyle: end
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: false
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/LineLength:
  Enabled: false # TODO reenable me
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 4
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/RescueEnsureAlignment:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/EmptyWhen:
  Enabled: false
Lint/FloatComparison:
  Enabled: false
Lint/IdentityComparison:
  Enabled: true
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/ParenthesesAsGroupedExpression:
  Enabled: false
Lint/RaiseException:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/SuppressedException:
  Enabled: false
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UnreachableLoop: 
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Lint/UselessTimes:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Max: 10
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
#  Max: 120
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/ConstantName:
  Enabled: false
Naming/FileName:
  Enabled: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Security/Open:
  Enabled: false
Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: separated
Style/ArgumentsForwarding:
  Enabled: true
Style/ArrayCoercion:
  Enabled: false
Style/Attr:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: true
Style/BlockComments:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining
Style/CaseEquality:
  Enabled: false
Style/CaseLikeIf:
  Enabled: true
Style/CharacterLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/CombinableLoops:
  Enabled: true
Style/CommentAnnotation:
  Enabled: false
Style/CollectionCompact:
  Enabled: true
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/Documentation:
  Enabled: false # FIXME reenable me
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/DoubleNegation:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
Style/FormatString:
  EnforcedStyle: percent
Style/FormatStringToken:
  Enabled: false
Style/GlobalStdStream:
  Enabled: true
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashLikeCase:
  Enabled: true
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfUnlessModifierOfIfUnless:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: true
Style/MethodCallWithArgsParentheses:
  Enabled: true
  EnforcedStyle: omit_parentheses
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/MutableConstant:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MultipleComparison:
  Enabled: false
Style/NegatedIfElseCondition:
  Enabled: false
Style/NestedTernaryOperator:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/OptionalBooleanParameter:
  Enabled: false # TODO consider enabling
Style/ParallelAssignment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%r': //
    '%w': ()
    '%W': ()
Style/PerlBackrefs:
  Enabled: false
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true
Style/RegexpLiteral:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SingleArgumentDig:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: false
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/StringConcatenation:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/SwapValues:
  Enabled: true
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TernaryParentheses:
  Enabled: false # TODO consider reenabling
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
RSpec/BeforeAfterAll:
  Enabled: false
RSpec/ContextWording:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false
RSpec/EmptyExampleGroup:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/ExampleWording:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/VoidExpect:
  Enabled: false
RSpec/BeEql:
  Enabled: false # NOTE: can't enable since be <float> doesn't work on JRuby
